[project]
name = "HuRAG"
version = "0.1.0"
description = "HuRAG, A TH-GraphRAG Application From QuestYard."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "aiomysql>=0.3.2",
    "fastapi>=0.123.0",
    "gunicorn>=23.0.0",
    "igraph>=1.0.0",
    "json-repair>=0.54.2",
    "langchain-text-splitters>=1.0.0",
    "markitdown[all]>=0.1.4",
    "openai>=2.8.1",
    "pymilvus>=2.6.4",
    "pymilvus-model>=0.3.2",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "typer>=0.20.0",
    "uuid6>=2025.0.1",
    "uvicorn>=0.38.0",
    "torch>=2.9.1; sys_platform == 'win32'",
    "torch>=2.9.1; sys_platform == 'linux'",
    "torch>=2.2.2; sys_platform == 'darwin' and platform_machine == 'x86_64'",
    "embedding-service",
]

[project.scripts]
hurag = "hurag.cli.kb_cli:app"
corpus = "hurag.cli.corpus_cli:app"
kgraph = "hurag.cli.kg_cli:app"

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
]

[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'x86_64'",
    "sys_platform == 'win32'",
    "sys_platform == 'linux'",
]

[tool.uv.sources]
embedding-service = { path = "../embedding-service", editable = true }

